trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: credentials
  - name: NODEVER
    value: 14.x

stages:
  - stage: Publish
    displayName: Publish Caliper
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    jobs:
      - job: PublishCaliper
        displayName: "Publish Caliper to NPM and DockerHub"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: .build/publish-caliper.sh
            displayName: Publish Caliper
            env:
              NPM_TOKEN: "$(npm)"
              DOCKER_USER: "$(DockerHub-Username)"
              DOCKER_TOKEN: "$(DockerHub-Password)"
